# Gunakan image base dari node
FROM node:18

# Set direktori kerja di container
WORKDIR /app

# Copy package.json dan package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy semua file ke dalam direktori kerja
COPY ./src/server /app/src/server

# Expose port yang digunakan Express.js
EXPOSE 3000

# Jalankan aplikasi Express.js
CMD ["npm", "start"]
